### ISSUE TITLE
Support for Safe contracts 1.2.0

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#362]
# What is this feature about? (1 sentence)
This will add support for the Safe contracts 1.2.0

# Why is it needed? What is the value? For whom do we build it?
The Gnosis Safe contracts v1.2.0 have passed audit and bug bounty period. So we can make them available for users.

# High-level overview of the feature
- 1.2.0 is a verified contract version in the Safe settings.
- Web ticket: gnosis/safe-react#1383

# Misc

- Mastercopy 1.2.0 https://etherscan.io/address/0x6851d6fdfafd08c0295c392436245e5bc78b0185
- https://github.com/gnosis/safe-contracts/releases/tag/v1.2.0

# Phase 1 

- [ ] Add address (`0x6851d6fdfafd08c0295c392436245e5bc78b0185`) to list of known implementation versions
- [ ] Show version 1.2.0 where applicable (do not ask user to upgrade if version is lower than 1.2.0)
  - [ ] Creation transaction (never ask user to upgrade)
  - [ ] Tx details for changeMasterCopy (never ask user to upgrade)
  - [ ] Safe settings (show "Up to date" for either 1.1.1 and 1.2.0 

# Updates

- Nov 23, Tobi: Add open questions
- Jan. 7, Dirk: Add Ticket contents for iOS/Android / Open Questions removed
- Jan. 18, Dirk: Epic split because phase 2 is blocked by gnosis/safe-react#1383

**Comment by Uxio0** [comment]
Current support on services:

**Comment by Uxio0** [comment]
Current support on services:
- [ ] Relay
- [ ] Transaction
- [ ] Notifications

**Comment by liliya-soroka** [comment]
Verified
app version:
ios - 2.9.0 (294)
android - 2..9.0 -1991rc
