### ISSUE TITLE
Ledger Nano X support on mobile

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#404]
# Problem to solve

#449 

# Requirements

- [x] Users can connect their Ledger on mobile
- [x] Users can sign txs with their Ledger on mobile
- [ ] Users receive signing requests on mobile when connected Ledger account is an owner of the Safe

# Spec

- specification https://docs.google.com/document/d/1DhM_jXs3WeRYw6oDHz7qljQU-HXWYSMEXFhi2B3Hbk4/edit?usp=sharing
- design - https://www.figma.com/file/KixqaQmQj5i1XY933JX6kS/Safe-iOS?node-id=225%3A22660
