### ISSUE TITLE
Add address book on mobile v1

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#408]
# Problem to solve

#457   

# Requirements

- [x] User can view address book entries
- [x] User can add address book entries
- [x] User can remove address book entries
- [x] User can import address book 
- [x] User can export address book 

# Links
- Specs doc: https://docs.google.com/document/d/1CimZeoy6HlA_DBic9ZTeyNphbVKivuqjc9EnDzCta_U/edit#

**Comment by DmitryBespalov** [comment]
- "Add to address book" from transaction details or other places?
- Use Address Book labels for known addresses logic throughout the app
