### ISSUE TITLE
Display decoded and raw tx data for all tx types on tx details

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#459]
# Problem to solve

#441 

Partially also #448 

# Requirements

- [ ] User can examine advanced info about the Safe tx in _tx queue_ for all tx types
  - `safeTxHash`
  - `nonce`
  - `to`
  - `value`
  - `data` - no need to display in full, being able to copy is sufficient
  - `operatiom`
  - `safeTxGas`
  - `baseGas`
  - `gasPrice`
  - `gasToken`
  - `refundReceiver`
  - `signatures`
- [ ] User can examine advanced info about the Safe tx in _tx history_ for all tx types
- [ ] If available user can view decoded tx data in _tx queue_ for all tx types
- [ ] If available user can view decoded tx data in _tx history_ for all tx types

### Links
- Requirements doc: https://docs.google.com/document/d/1c55mYT8pJXwJ5tDdzjtWfnYNKl3_aW1PlU0D_xqDySY/edit#

**Comment by liliya-soroka** [comment]
Verified for mobile app 
android " 3.2.0 -3391rc
ios -3.3.0 (621)

**Comment by liliya-soroka** [comment]
@katspaugh and @lukasschor , the Epic is implemented on mobile and will be available on prod in the next release.
Are we going to include it into the product backlog for web app too ? ( according to labels it should be implemented on both mobile and web )
