### ISSUE TITLE
Show module address for module txs on tx details

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#466]
# Problem to solve

#447  

# Requirements

- [x] User can view module address for module txs on tx details
- [x] In case it's a known address, the human readable name is used.
- [x] In case the module address is in the address book, the address book name is used.

# Links
[Spec document](https://docs.google.com/document/d/1SqVHzzwu2_NybT_typGMwpKchWf74NZWNHBzxu_iQhQ/edit)

**Comment by liliya-soroka** [comment]
Implemented and verified on mobile:
android 3.2.0 -3369rc
ios - 3.3.0 (672)
