### ISSUE TITLE
Allow to connect 3rd party mobile wallets via WalletConnect to Safe mobile app

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#468]
# Problem to solve

#449  

# Requirements

- [x] Users can connect 3rd party mobile wallet
- [x] Users can sign txs with a 3rd party mobile wallet
- [x] Users receive signing requests via push on mobile when connected 3rd party mobile wallet account is an owner of the Safe

# Misc

- Andrey has implemented this as experimental feature on iOS already.

**Comment by liliya-soroka** [comment]
Verified ( ios only )
app version 3.5.0 (749)
