### ISSUE TITLE
[EPIC] Improving tx info/data

### ISSUE THREAD

**Issue by johannesmoormann** [gnosis/safe#497]
Overview:

This epic contains improvement proposals that try to improve the available information a user is able to see and access in the transaction flow including the tx history. 

1. Web only (already implemented on mobile, might need a design for web):
- [ ] https://github.com/gnosis/safe/issues/459

2. Web only (based on 1., only usable for mobile once tx execution is available):
- [x] https://github.com/gnosis/safe/issues/460

3. Web only (already implemented on mobile, might need a design for web)
- [x] https://github.com/gnosis/safe/issues/466

Lower priority:

- [ ] https://github.com/gnosis/safe/issues/473

Research

https://github.com/gnosis/safe/issues/467
