### ISSUE TITLE
What's new dialogue in Mobile App 

### ISSUE THREAD

**Issue by sche** [gnosis/safe#507]
# Problem
https://github.com/gnosis/safe-pm/issues/18 

# What is this feature about? (1 sentence)
Display to users what is new with every release. Encourage users to provide feedback.

# High-level overview of the feature
- [ ] Display what's new dialogue for every new app version
- [x] Decide if we hardcode this information or if we take it from a remote source
- [ ] Encourage users to provide feedback on what should we implement next

# KPIs
- Increase features requests for mobile from users
- Improve retention to the mobile app

# Links
[Requirements](https://docs.google.com/document/d/1tacgEhp-e5WED3IoN1pMuPi3Y1FPxdwuihtuSiH8qA0/edit)

**Comment by lukasschor** [comment]
Potential the Intercom SDK could be leveraged for this.

**Comment by DmitryBespalov** [comment]
### Alternative 1: WhatsNewKit + HardCoded/Backend Data source/Firebase data source
Found  a ready-made library: https://cocoapods.org/pods/WhatsNewKit

It supports UI customization, and also allows to get the 'what's new' information however we like it to do: either from hard-coded values, or from a json backend (data source needs to be implemented though).

We could go with the hard-coded values for the following 2-3 releases, and meanwhile ask backend for a new endpoint implementation.

![https://raw.githubusercontent.com/SvenTiigi/WhatsNewKit/gh-pages/readMeAssets/WhatsNewKit.gif](https://raw.githubusercontent.com/SvenTiigi/WhatsNewKit/gh-pages/readMeAssets/WhatsNewKit.gif)

### Alternative 2: Intercom
Intercom allows to show a 'post' to users based on some conditions. I would assume that this would mean we'll present our Changelog to users with then new app version. I assume this option would not require any changes at all if we'll add the Intercom SDK anyway. However, we won't be able to have a custom UI for this "what's new" screen.

![image.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/5a87dac1-4a77-4f59-a6e3-0721bb677bc4)
![image.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/04925f37-9acf-4cae-8d5a-5c70d93a3941)

### Alternative 3: Custom UI
We could create our own custom UI - the way we like. Then, this would have the same data source flexibility as Option 1: it can support hard-coded, or backend, or firebase data sources when/if needed.



### Conclusion
Tech prototype needed to try out and explore the options.

**Comment by liliya-soroka** [comment]
Verified
the major issue is reported separately 

app version 3.6.0 (796)
