### ISSUE TITLE
Onboarding improvements v1

### ISSUE THREAD

**Issue by sche** [gnosis/safe#516]
## Problem 
[Many users drop on mobile after the first App install](https://github.com/gnosis/safe-pm/issues/16)

The goal of this epic is to improve the onboarding experience and to increase the amount of onboarded users (new users that added their safe).

 ## Solution

- [x] Offer to setup passcode at a later stage - after importing the first safe
- [x] Have explicit actions "Load existing Safe" and "Create new Safe"
- [x] Add a placeholder screen for "Create new Safe"

## Links
[Requirements](https://docs.google.com/document/d/1j4iLeGa2iOKWA2aJiU-9Xa1zyeQCiDJiM34MnMQzo0U/edit#)

**Comment by liliya-soroka** [comment]
Verified ( ios only)
app version 3.5.0 (749)
