### ISSUE TITLE
Move Dapps tab out of experimental

### ISSUE THREAD

**Issue by sche** [gnosis/safe#518]
# What is this feature about? (1 sentence)
We want to move the "Dapps" tab out of experimental to collect more data on how users use it.
Current data demonstrate that those users who discovered the "Experimental" tab enable the "Dapps" tab with high probability and often initiate new transactions using WalletConnect.

# High-level overview of the feature
- [x] Move the "Dapps" tab out of experimental
- [x] Don’t display the "SafeTxGas" field for incoming transactions for contracts v1.3.0
- [x] Use tx estimation endpoint to get current contract nonce
- [x] Show “Edit tx parameters” screen for incoming transactions in a popover
- [x] Add a link to the help article on transaction parameters on the “Edit tx parameters” screen
- [x] Track help link clicks
- [x] Improve readability of connected dapps on the "Dapps" tab
- [x] Add CowSwap exchange to the default dapps list on supported networks
- [x] Update "default dapps" list with most used dapps

# Expected outcome
- Users will initiate more transactions using a mobile device
- Retention of mobile users will increase

# Links
[Requirements](https://docs.google.com/document/d/1muSp2dk-_cepH0ZHt9xZtpF8Bam7-bYHgfkdbcNnGVM/edit#)

**Comment by liliya-soroka** [comment]
Verified ( ios only)
app version 3.5.0 (749)
